input_folder = './input/data_set_phase1'
plan_items = ['distance', 'eta', 'price', 'transport_mode']

type_dict ={
 'sid':'int',
 'pid':'str',


 'day':'int',
 'weekday':'int',
 'hour':'int',
 'weekend':'int',
 'o0':'float',
 'o1':'float',
 'd0':'float',
 'd1':'float',

 #
 # 'order',
 # 'distance',
 # 'eta',
 # 'price',
 # 'transport_mode',
 # 'order_2',
 # 'distance_2',
 # 'eta_2',
 # 'price_2',
 # 'transport_mode_2',
 # 'order_3',
 # 'distance_3',
 # 'eta_3',
 # 'price_3',
 # 'transport_mode_3',
 # 'order_4',
 # 'distance_4',
 # 'eta_4',
 # 'price_4',
 # 'transport_mode_4',
 # 'order_5',
 # 'distance_5',
 # 'eta_5',
 # 'price_5',
 # 'transport_mode_5',
 # 'order_6',
 # 'distance_6',
 # 'eta_6',
 # 'price_6',
 # 'transport_mode_6',
 # 'order_7',
 # 'distance_7',
 # 'eta_7',
 # 'price_7',
 # 'transport_mode_7',
 # 'order_8',
 # 'distance_8',
 # 'eta_8',
 # 'price_8',
 # 'transport_mode_8',
 # 'order_9',
 # 'distance_9',
 # 'eta_9',
 # 'price_9',
 # 'transport_mode_9',
 # 'order_10',
 # 'distance_10',
 # 'eta_10',
 # 'price_10',
 # 'transport_mode_10',
 # 'order_11',
 # 'distance_11',
 # 'eta_11',
 # 'price_11',
 # 'transport_mode_11',
 # 'o_seq_0',
 # 'o_seq_1',
 # 'o_seq_2',
 # 'o_seq_3',
 # 'o_seq_4',
 # 'o_seq_5',
 # 'o_seq_6',

 'click_mode':'str'
}